logging:
  level:
    root: info
    org.springframework.web: info

spring:
  profiles:
    active: development

---
# this is a development profile
# use it for local development and testing
spring:
  profiles: development
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      driverClassName: org.postgresql.Driver
      username: postgres
      password: dbpwd
      initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

telegram:
  token: 1153088687:AAGlMcZ6W2qvE_YaWlYkXTkg9W2Yg8XZL0U
  name: English bot

server:
  port: 8090
  servlet:
    context-path: /
