logging:
  level:
    root: info
    org.springframework.web: info

spring:
  profiles:
    active: development

---
# this is a development profile
# use it for local development and testing
spring:
  profiles: development
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      driverClassName: org.postgresql.Driver
      username: postgres
      password: dbpwd
      initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

telegram:
  token: 1153088687:AAGlMcZ6W2qvE_YaWlYkXTkg9W2Yg8XZL0U
  name: English bot

server:
  port: 8090
  servlet:
    context-path: /


---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://ec2-34-195-233-155.compute-1.amazonaws.com:5432/d4kbbl55smkq8p
    driverClassName: org.postgresql.Driver
    username: krjpnhcpiaffrr
    password: 4be52fe389621dbc04b662f914767ad3bce080840fbaa2da92914f38566ae2d8
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

telegram:
  token: 1154875410:AAHor7XVEQ2EJGuEJU2y_PFDx122P2ePAcs
  bot-url: https://arcane-ocean-32556.herokuapp.com/
  name: English bot

server:
  servlet:
    context-path: /
