logging:
  level:
    root: info
    org.springframework.web: info

spring:
  profiles:
    active: development

---
# this is a development profile
# use it for local development and testing
spring:
  profiles: development

telegram:
  token: 1153088687:AAGlMcZ6W2qvE_YaWlYkXTkg9W2Yg8XZL0U
  name: English bot
  bot.server.url: https://c8340a23baed.ngrok.io


server:
  port: 8090
  servlet:
    context-path: /