logging:
  level:
    root: info
    org.springframework.web: info

spring:
  profiles:
    active: development

---
# this is a development profile
# use it for local development and testing
spring:
  profiles: development
  datasource:
      url: jdbc:h2:./src/main/resources/db/englishbot
      driverClassName: org.h2.Driver
      username: sa
      password:
  h2.console:
    enabled: true
    path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

telegram:
  token: 1154875410:AAHor7XVEQ2EJGuEJU2y_PFDx122P2ePAcs
  name: English bot
  bot.server.url: https://1ba9b9aa8ea3.ngrok.io

server:
  port: 8090
  servlet:
    context-path: /
