name: Deploy

on:
  push:
    branches:
      - feature/EN-57-prepare-prod
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "whispering-hamlet-22946"
          heroku_email: "agienko.sergiy@gmail.com"